# Generated by Django 5.0.6 on 2024-06-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_event_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='club_images/'),
        ),
    ]
