# Generated by Django 5.0.6 on 2024-06-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_event_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
