# Generated by Django 5.0.6 on 2024-06-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_event_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
